version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: local-postgres
    environment:
      POSTGRES_DB: me_db
      POSTGRES_USER: me_user
      POSTGRES_PASSWORD: me_test1
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local-net

volumes:
  postgres-data:
    driver: local

networks:
  local-net:
    driver: bridge
